const MessageType = {
  JOIN_MEETING: "JOIN_MEETING",
  CREATE_MEETING: "CREATE_MEETING",
  MEETING_CREATED: "MEETING_CREATED",
  LEAVE_MEETING: "LEAVE_MEETING",
  SELECT: "SELECT",
  DELETE: "DELETE",
  CREATE_OBJECT: "CREATE_OBJECT",
};

module.exports = MessageType;
