const MessageType = {
  JOIN_MEETING: "JOIN_MEETING",
  CREATE_MEETING: "CREATE_MEETING",
  MEETING_CREATED: "MEETING_CREATED",
  MEETING_JOINED: "MEETING_JOINED",
  LEAVE_MEETING: "LEAVE_MEETING",
  SELECT: "SELECT",
  DELETE: "DELETE",
  CREATE_OBJECT: "CREATE_OBJECT",
  DELETE_BROADCAST: "DELETE_BROADCAST",
  CHANGE_BROADCAST: "CHANGE_BROADCAST",
  BOARD_UPDATE: "BOARD_UPDATE",
  USER_BROADCAST: "USER_BROADCAST",
};

module.exports = MessageType;
