const MessageType = {
  JOIN_MEETING: "JOIN_MEETING",
  CREATE_MEETING: "CREATE_MEETING",
  MEETING_CREATED: "MEETING_CREATED",
  MEETING_JOINED: "MEETING_JOINED",
  LEAVE_MEETING: "LEAVE_MEETING",
  SELECT: "SELECT",
  DELETE: "DELETE",
  EDIT: "EDIT",
  CREATE_OBJECT: "CREATE_OBJECT",
  DELETE_BROADCAST: "DELETE_BROADCAST",
  CHANGE_BROADCAST: "CHANGE_BROADCAST",
  BOARD_UPDATE: "BOARD_UPDATE",
  USER_BROADCAST: "USER_BROADCAST",
  CLEAR_WHITEBOARD: "CLEAR_WHITEBOARD",
  POSITION_CHANGE: "POSITION_CHANGE",
  OBJECT_CREATED: "OBJECT_CREATED",
};

module.exports = MessageType;
